### ISSUE TITLE
Nice params code!

### ISSUE THREAD

**Issue by sb8244** [atomaka/railschallenge-city-watch#2]
Hey Andrew. Loved seeing your application controller handling of unpermitted params. I didn't realize that the behavior of how to handle it could be changed like you did. Excellent!

That was the most hacky part of my submission since I handled it manually.

**Comment by atomaka** [comment]
Thanks, @sb8244!  I struggled with this for a bit before discovering that you could [raise exceptions on unpermitted parameters via configuration](https://github.com/atomaka/railschallenge-city-watch/blob/03cbda5877cd966b4d1a407f52a996fd2f07daa3/config/environments/development.rb#L16).  I eventually refactored after realizing I could set it in the controller.  I'm still undecided on which I prefer.

Congratulations on your first place finish!
